# Origin protection layer.
#
# All quickship apps under this platform sit behind a CloudFront distribution
# protected by an AWS WAFv2 WebACL. The WebACL only allows requests carrying
# a shared secret in the X-Origin-Secret header. Cloudflare adds this header
# on every request forwarded to origin via a single shared Transform Rule.
#
# Threat model:
#   - Direct hits to the Function URL → blocked by AWS IAM (auth_type=AWS_IAM + OAC).
#   - Direct hits to the CloudFront *.cloudfront.net URL → blocked by WAF (no header).
#   - Direct hits to the user-facing hostname → blocked by Cloudflare Access (auth challenge).
#
# Rotation point: tainting random_password.origin_secret regenerates the secret;
# both the WAF rule and Cloudflare Transform Rule update atomically on next apply.

resource "random_password" "origin_secret" {
  length  = 64
  special = false # header-safe charset only
  upper   = true
  lower   = true
  numeric = true
}

resource "aws_ssm_parameter" "origin_secret" {
  name        = "${local.ssm_root}/_platform/origin-secret"
  description = "Shared secret. Cloudflare injects this in X-Origin-Secret; WAF rejects requests missing it. Generated by random_password — TF-managed end to end."
  type        = "SecureString"
  value       = random_password.origin_secret.result
  tags        = local.common_tags
}

# WAFv2 WebACL — must live in us-east-1 because scope = CLOUDFRONT.
resource "aws_wafv2_web_acl" "tinyapp_origin" {
  provider = aws.us_east_1

  name        = "${var.name_prefix}-origin-protection"
  description = "Quickship origin protection. Allows requests with the correct X-Origin-Secret header, blocks all others"
  scope       = "CLOUDFRONT"

  default_action {
    block {}
  }

  rule {
    name     = "allow-with-shared-secret"
    priority = 1

    action {
      allow {}
    }

    statement {
      byte_match_statement {
        positional_constraint = "EXACTLY"
        search_string         = random_password.origin_secret.result

        field_to_match {
          single_header {
            name = "x-origin-secret"
          }
        }

        text_transformation {
          priority = 0
          type     = "NONE"
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "${var.name_prefix}-origin-allow"
      sampled_requests_enabled   = true
    }
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "${var.name_prefix}-origin-protection"
    sampled_requests_enabled   = true
  }

  tags = local.common_tags
}

# Cloudflare Transform Rule — single shared rule on the apex zone that adds
# X-Origin-Secret to every request forwarded to origin. Phase
# http_request_late_transform runs after Access auth and before origin fetch.
#
# Reads zone_id from the bootstrap-created SSM placeholder; fails clearly if
# the placeholder still holds REPLACE_ME (operator hasn't populated it).
data "aws_ssm_parameter" "platform_cf_zone_id" {
  name       = aws_ssm_parameter.cloudflare_zone_id.name
  depends_on = [aws_ssm_parameter.cloudflare_zone_id]

  lifecycle {
    postcondition {
      condition     = self.value != "REPLACE_ME"
      error_message = "/${var.name_prefix}/cloudflare/zone_id is still REPLACE_ME. Populate it with the real Cloudflare zone ID, then re-apply."
    }
  }
}

resource "cloudflare_ruleset" "origin_secret_inject" {
  zone_id     = data.aws_ssm_parameter.platform_cf_zone_id.value
  name        = "${var.name_prefix}-origin-secret-inject"
  description = "Inject X-Origin-Secret on all requests routed to origin. Verified by AWS WAF on CloudFront."
  kind        = "zone"
  phase       = "http_request_late_transform"

  rules = [
    {
      description = "Set X-Origin-Secret on every request in this zone"
      expression  = "true"
      action      = "rewrite"
      enabled     = true
      action_parameters = {
        headers = {
          "X-Origin-Secret" = {
            operation = "set"
            value     = random_password.origin_secret.result
          }
        }
      }
    },
  ]
}
